#!/usr/bin/env bash

#set -o xtrace
set -e

cd $(cd $(dirname "$0") && pwd)

if ! command docker &>/dev/null; then
  echo "ERROR: docker binary not found" >&2
  exit 1
elif [ -f /.dockerenv ]; then
  echo "ERROR: cannot run this script from within Docker container" >&2
  exit 1
elif ! docker ps &> /dev/null; then
  DOCKER="sudo docker"
else
  DOCKER="docker"
fi

# Function to detect if the system has a GUI
has_gui() {
  if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
    return 0
  elif dpkg -l | grep -E '^ii\s+(xorg|xserver|wayland|gnome|kde|xfce|lxde|mate)' >/dev/null; then
    return 0
  fi

  return 1
}

if [ -z "$TARGET_ENV" ]; then
  if has_gui; then
    TARGET_ENV=x
  else
    TARGET_ENV=term
  fi
fi

source ./env.sh
export TARGET_ENV

$DOCKER compose --progress plain \
        run \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd) \
        builder

( cd emacs && sudo make install )

echo "done."